# Generated by Django 5.1.4 on 2025-05-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0002_account_converted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="manager_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
