# Generated by Django 5.1.4 on 2025-05-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0003_account_email_account_manager_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="manager_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
