# Generated by Django 5.0.1 on 2025-05-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0004_contact_manager_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="lead_source",
            field=models.CharField(
                choices=[
                    ("website_demo", "Website - {Demo}"),
                    ("website_live", "Website - {Live}"),
                    ("phone", "Phone Inquiry"),
                    ("referral", "Referral"),
                    ("email", "Email"),
                    ("social_media", "Social Media"),
                    ("trade_show", "Trade Show"),
                    ("other", "Other"),
                    ("email_campaign", "Email Campaign"),
                    ("cold_call", "Cold Call"),
                    ("event", "Event"),
                ],
                default="website_demo",
                max_length=20,
            ),
        ),
    ]
