# Generated by Django 5.0.1 on 2025-05-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0005_alter_lead_lead_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="branch_manager_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="branch_manager_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="branch_manager_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="manager_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="branch_manager_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="branch_manager_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
