# Generated by Django 5.0.1 on 2025-06-01 11:42

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0006_account_branch_manager_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllotManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "manager_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="account",
            name="branch_manager_username",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="branch_manager_username",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="branch_manager_username",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="manager_username",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="branch_manager_username",
        ),
        migrations.RemoveField(
            model_name="task",
            name="branch_manager_username",
        ),
        migrations.AlterField(
            model_name="lead",
            name="lead_source",
            field=models.CharField(
                choices=[
                    ("website_demo", "Website - {Demo}"),
                    ("website_live", "Website - {live}"),
                    ("phone", "Phone Inquiry"),
                    ("referral", "Referral"),
                    ("email", "Email"),
                    ("social_media", "Social Media"),
                    ("trade_show", "Trade Show"),
                    ("other", "Other"),
                    ("email_campaign", "Email Campaign"),
                    ("cold_call", "Cold Call"),
                    ("event", "Event"),
                ],
                default="website",
                max_length=20,
            ),
        ),
    ]
